### ISSUE TITLE
Organised file structure

### ISSUE THREAD

**Issue by jokosanyang** [fac19/week10-camko#10]
Good job architecting the file structure. It's really easy to see where everything is, with each component folder containing the related styling and (hopefully coming-soon 😛) tests.

The only thing I would question is whether the mp3 files belong in the `/utils` folder? Have you considered adding an `/assets` folder for images and mp3 files?

![image](https://user-images.githubusercontent.com/43584074/81348984-01b0cb80-90b7-11ea-8b4d-6b821b6a1763.png)

**Comment by hannahgooding** [comment]
Agreed, really clear and well organised file structure so was a pleasure to code review!
