### ISSUE TITLE
H1 overload

### ISSUE THREAD

**Issue by jokosanyang** [fac19/week10-camko#12]
Ideally, we should only have one h1 element on the page. By setting the title of each card to a h1, we end up with 17. 😅 
Maybe they could be h2s if you had a h1 heading on the page? Or maybe just bold/styled p tags.

https://github.com/fac19/week10-camko/blob/fdc50beb6479435760c13de046bfe5f0d17a0594/src/components/fighter/fighter.js#L24-L29

PS. So curious as to why Giovanna's been singled out like this. 😂 
![curious](https://media.giphy.com/media/LKf4i5Tvt7mE0/giphy.gif)

**Comment by hannahgooding** [comment]
Is it because Gio's name on GitHub is too long? We were wondering about this too haha!

**Comment by akomiqaia** [comment]
Yeah let's right :D no long names allowed
