### ISSUE TITLE
I defeated Gregor! :trophy:

### ISSUE THREAD

**Issue by jokosanyang** [fac19/week10-camko#9]
It was a tough one. He had more Attack than me, but I got him. 
Trust me when I say I'm going to be sending him these screenshots on random days for the rest of forever. 

<img width="1080" alt="Screenshot 2020-05-07 at 20 27 04" src="https://user-images.githubusercontent.com/43584074/81336834-f1dabc80-90a1-11ea-8750-9bf9b87814d0.png">
<img width="997" alt="Screenshot 2020-05-07 at 20 27 11" src="https://user-images.githubusercontent.com/43584074/81336853-facb8e00-90a1-11ea-8a75-0a9654cebefc.png">

Fun concept for a game!

**Comment by akomiqaia** [comment]
thanks a lot <3
